# Generated by Django 3.2.5 on 2021-07-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee', models.OneToOneField(db_column='Employee_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('employee_name', models.CharField(db_column='Employee_Name', max_length=45)),
                ('birth_date', models.DateField(db_column='Birth_Date')),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=11)),
                ('national_number', models.CharField(db_column='National_Number', max_length=14)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('emp_type', models.IntegerField(db_column='Emp_Type')),
            ],
            options={
                'db_table': 'EMPLOYEES',
                'managed': False,
            },
        ),
    ]
