# Generated by Django 3.2.5 on 2021-07-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.AutoField(db_column='Crew_ID', primary_key=True, serialize=False)),
                ('crew_status', models.CharField(db_column='Crew_Status', max_length=45)),
                ('number_of_accidents', models.IntegerField(db_column='Number_Of_Accidents')),
                ('current_accident', models.IntegerField(blank=True, db_column='Current_Accident', null=True)),
            ],
            options={
                'db_table': 'CREW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager', models.OneToOneField(db_column='Manager_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.employees')),
            ],
            options={
                'db_table': 'MANAGER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(db_column='Station_ID', primary_key=True, serialize=False)),
                ('station_type', models.IntegerField(db_column='Station_Type')),
                ('place_long', models.FloatField(db_column='Place_Long')),
                ('place_lat', models.FloatField(db_column='Place_Lat')),
                ('governerate', models.CharField(db_column='Governerate', max_length=45)),
                ('city', models.CharField(db_column='City', max_length=45)),
                ('available_cars', models.IntegerField(db_column='Available_Cars')),
                ('car_numbers', models.IntegerField(db_column='Car_Numbers')),
            ],
            options={
                'db_table': 'STATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationEmployees',
            fields=[
                ('station_employee', models.OneToOneField(db_column='Station_Employee_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.employees')),
                ('job_title', models.CharField(db_column='Job_Title', max_length=45)),
                ('number_of_accidents', models.IntegerField(blank=True, db_column='Number_Of_Accidents', null=True)),
            ],
            options={
                'db_table': 'STATION_EMPLOYEES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.IntegerField(db_column='Vehicle_ID', primary_key=True, serialize=False)),
                ('vehicle_status', models.CharField(db_column='Vehicle_Status', max_length=45)),
                ('vehicle_number', models.CharField(db_column='Vehicle_Number', max_length=24)),
                ('special_case', models.CharField(blank=True, db_column='Special_Case', max_length=45, null=True)),
            ],
            options={
                'db_table': 'VEHICLES',
                'managed': False,
            },
        ),
    ]
