# Generated by Django 3.2.5 on 2021-07-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_crew_manager_station_stationemployees_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casualties',
            fields=[
                ('casualties_id', models.AutoField(db_column='Casualties_ID', primary_key=True, serialize=False)),
                ('casualty_name', models.CharField(blank=True, db_column='Casualty_Name', max_length=45, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=45, null=True)),
                ('gender', models.IntegerField(db_column='Gender')),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'CASUALTIES',
                'managed': False,
            },
        ),
    ]
